- name: Log on which Distro or OS Docker is going to be installed
  debug:
    msg: "The distro is: {{ ansible_distribution }}"

- name: Run Docker installation on MacOS
  include_tasks: docker-macosx.yml
  when: ansible_distribution == "MacOSX"

- name: Run Docker installation on Ubuntu
  include_tasks: docker-ubuntu.yml
  when: ansible_os_family == "Debian"